### Create Task
POST http://127.0.0.1:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWExYTBmOWQ1YmUzZTdhZWRkZWYwMDMiLCJpYXQiOjE3MDUwOTEzMjJ9.loa4PeW6kGcPukm2h7mndqSw4sg9LmTEDfTsfn4V7RA

{
    "description": "Task 5",
    "completed": false
}

### Get All Task
GET http://127.0.0.1:3000/tasks?sort=description:desc&limit=2&completed=true
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWExYTBmOWQ1YmUzZTdhZWRkZWYwMDMiLCJpYXQiOjE3MDUwOTEzMjJ9.loa4PeW6kGcPukm2h7mndqSw4sg9LmTEDfTsfn4V7RA

### Get One Tasks
GET http://127.0.0.1:3000/tasks/659f0ce6b2cbcc925eaca6be
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTlmMTViNmFmN2UyNTk0NzExZjMyNmMiLCJpYXQiOjE3MDQ5MjQ1OTh9.Vs_biSxWBP08jK_7TmynCUu7JVmaKJV7dvdBY15LFFM

### Update One Task
PATCH http://127.0.0.1:3000/tasks/659f0ce6b2cbcc925eaca6be
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTlmMTViNmFmN2UyNTk0NzExZjMyNmMiLCJpYXQiOjE3MDQ5MjQ1OTh9.Vs_biSxWBP08jK_7TmynCUu7JVmaKJV7dvdBY15LFFM

{
    "completed": true
}

### Delete One Task
DELETE  http://127.0.0.1:3000/tasks/659f109a0360080c5b98fe68
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTlmMTViNmFmN2UyNTk0NzExZjMyNmMiLCJpYXQiOjE3MDQ5MjQ1OTh9.Vs_biSxWBP08jK_7TmynCUu7JVmaKJV7dvdBY15LFFM