### Create User
POST http://127.0.0.1:3000/users
Content-Type: application/json

{
    "name": "Oldemar",
    "email": "oldemego@email.com",
    "password": "SamplePasswod0189",
    "age": 22
}

### Get All User
GET http://127.0.0.1:3000/users
Accept: application/json

### Get One User
GET http://127.0.0.1:3000/users/659af4dc7c302e3e83b6c730
Accept: application/json

### Update One User
PATCH http://127.0.0.1:3000/users/659c8c895a9f6e8bfeebd6a8
Accept: application/json
Content-Type: application/json

{
    "name": " Oldemar Jesus ",
    "password": "Teste1234"
}

### Delete One User
DELETE http://127.0.0.1:3000/users/659af4dc7c302e3e83b6c730
Accept: application/json