### Upload User Profile Picture
POST http://localhost:3000/users/me/avatar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer <token here>

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="profile-pic.jpg"
Content-Type: image/jpeg

< <image full path>
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Delete User Profile Picture
DELETE http://localhost:3000/users/me/avatar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer <token here>